/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioDAO;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import model.Usuario;

/**
 *
 * @author quemu
 */
public class FormLogin extends javax.swing.JFrame {
    //lista de usuários
    List<Usuario> logins = new ArrayList();
    /**
     * Creates new form FormPrincipal
     */
    public FormLogin() {
        initComponents();
        configurarLogin();
        
        //leitura das informações do banco
        try {
            logins = new UsuarioDAO().listar();
        } catch (Exception e) {
            System.out.println("ERRO: "+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSenha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnRecuperar_senha = new javax.swing.JButton();
        lblImageLogin = new javax.swing.JLabel();
        btnCadatrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSenha.setText("Senha");

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setText("Usuário");

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
        });

        btnRecuperar_senha.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnRecuperar_senha.setText("Esqueci minha senha");
        btnRecuperar_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperar_senhaActionPerformed(evt);
            }
        });

        lblImageLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/login.png"))); // NOI18N

        btnCadatrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCadatrar.setText("Cadastrar");
        btnCadatrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadatrarActionPerformed(evt);
            }
        });
        btnCadatrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadatrarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRecuperar_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUsuario)
                            .addComponent(lblSenha)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(txtSenha)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCadatrar)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImageLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImageLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnCadatrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecuperar_senha)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRecuperar_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperar_senhaActionPerformed
        String security_question;
        int flag = 0;
        
        //loop de verificação da resposta informada
        while(flag == 0){
            while((security_question = JOptionPane.showInputDialog(null,"Dica de senha: ")).isEmpty()){
                JOptionPane.showMessageDialog(null,"A resposta está em branco!","\nSenha inválida!", JOptionPane.WARNING_MESSAGE);
            }
        
            for (Usuario item : logins) {
                if((item.getLogin()).equals(txtUsuario.getText()) && item.getResposta().equals(security_question)){
                    item.setSenha(JOptionPane.showInputDialog(null,"Informe uma nova senha: "));
                    int usr = new UsuarioDAO().atualizar(item);
                    flag = 1;
                }
            }
            if(flag == 0){
                JOptionPane.showMessageDialog(null,"A resposta está incorreta!","\nSenha inválida!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRecuperar_senhaActionPerformed

    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed
        login();
    }//GEN-LAST:event_btnLoginKeyPressed

    private void btnCadatrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadatrarActionPerformed
          FormCadastroUsuario novo = new FormCadastroUsuario(-1);
          novo.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_btnCadatrarActionPerformed

    private void btnCadatrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadatrarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadatrarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadatrar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRecuperar_senha;
    private javax.swing.JLabel lblImageLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void configurarLogin(){
        //posicionamento do formulario
        this.setLocationRelativeTo(null);

        //redimensionamento
        this.setResizable(false);
        
        this.setTitle("Controle Usuarios");
        //posicionamento do formulario
        this.setLocationRelativeTo(null);

        //redimensionamento
        this.setResizable(false);

        //foco do cursor no JTextField txtUsuario
        txtUsuario.requestFocus();
        //dica do botão
        btnLogin.setToolTipText("clique no botão para entrar no sistema");
        btnRecuperar_senha.setToolTipText("clique no botão para recuperar a senha de acesso");
    }
    
    private void login(){
        String senha = new String (txtSenha.getPassword());
        if(!logins.isEmpty() && !txtUsuario.getText().isEmpty() && !senha.isEmpty()){            
            for (Usuario lg : logins) {
                if(txtUsuario.getText().equals(lg.getLogin()) && MD5(senha).toUpperCase().equals(lg.getSenha().toUpperCase())){
                    FormPrincipal main_form = new FormPrincipal();
                    main_form.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null,"Verifique as informações e tente novamente.","Login",JOptionPane.ERROR_MESSAGE);
                    txtSenha.setText("");
                    txtSenha.requestFocus();
                }
            }
        }else if(txtUsuario.getText().isEmpty() && senha.isEmpty()){
            JOptionPane.showMessageDialog(null,"Usuário e/ou senha vazios, por favor verifique e tente novamente!");
//            login();
                txtUsuario.requestFocus();
        }else{
            JOptionPane.showMessageDialog(null,"Não existem usuários cadastrados!","Login",JOptionPane.INFORMATION_MESSAGE);
            txtUsuario.setText("");
            txtSenha.setText("");
            txtUsuario.requestFocus();
        }
    }
    
    private String MD5(String senha){
        MessageDigest m;
        try {
            m = MessageDigest.getInstance("MD5");
            m.reset();
            m.update(senha.getBytes(), 0, senha.length());
            BigInteger pwd1 = new BigInteger(1, m.digest());
            return senha = String.format("%1$032X", pwd1);
        } catch (Exception e) {
            return null;
        }
    }
}
